config system global
set ssl-min-proto-version TLSv1-1
end
config system interface
edit "port1"
set allowaccess "http" "ssh"
next
end
config firewall policy
edit 1
set srcintf "any"
set dstintf "any"
set srcaddr "all"
set dstaddr "all"
set service "ALL"
set schedule "always"
set action accept
next
end
