set system host-name juniper
set system services telnet
set system services ssh root-login allow
set firewall filter test term 1 from source-address 0.0.0.0/0
set firewall filter test term 1 then accept
set interfaces ge-0/0/0 unit 0 family inet filter input test
