"""CIS benchmark recommendation numbers for rules that fully implement them (SC-062).

Generated from the private CIS coverage catalogue (status "covered" only). Only benchmark names and
recommendation numbers are stored; CIS text is never copied into the repository. A reference means the
rule implements the recommendation for the configuration it can assess; it is not benchmark certification,
and vendor documentation remains the source for every default. Partial and verify mappings are omitted.
"""

from __future__ import annotations

CIS_BENCHMARKS: dict[str, str] = {
    "asa": "CIS Cisco ASA 9.x Firewall Benchmark v1.1.0",
    "checkpoint": "CIS Check Point Firewall Benchmark v1.1.0",
    "eos": "CIS Arista EOS Benchmark v1.0.0",
    "f5": "CIS F5 Networks Benchmark v1.0.0 (archived)",
    "fortigate74": "CIS FortiGate 7.4.x Benchmark v1.0.1",
    "ios17": "CIS Cisco IOS 17.x Benchmark v2.0.0",
    "iosxe17": "CIS Cisco IOS XE 17.x Benchmark v2.2.1",
    "junos": "CIS Juniper OS Benchmark v2.1.0",
    "panos11": "CIS Palo Alto Firewall 11 Benchmark v1.2.0",
}

CIS_RULE_REFERENCES: dict[str, tuple[tuple[str, str], ...]] = {
    "arista.eos.admin.idle_timeout": (("eos", "2.4.1"), ("eos", "2.6.2")),
    "arista.eos.admin.local_password_minimum_ineffective": (("eos", "2.1.3"),),
    "arista.eos.admin.login_banner": (("eos", "2.9.1"),),
    "arista.eos.admin.role_reference": (("eos", "2.3.1"),),
    "arista.eos.auth.nopassword_remote_login": (("eos", "2.1.1"),),
    "arista.eos.auth.root_login_enabled": (("eos", "2.1.4"),),
    "arista.eos.authentication.centralized": (("eos", "2.5.1"),),
    "arista.eos.authorization.commands": (("eos", "2.5.3"),),
    "arista.eos.authorization.exec": (("eos", "2.5.3"),),
    "arista.eos.control_plane.acl_empty": (("eos", "1.1.2"),),
    "arista.eos.control_plane.acl_no_enforcement": (("eos", "1.1.2"),),
    "arista.eos.control_plane.acl_reference": (("eos", "1.1.2"),),
    "arista.eos.control_plane.copp_class_no_enforcement": (("eos", "1.1.3"),),
    "arista.eos.control_plane.copp_class_reference": (("eos", "1.1.3"),),
    "arista.eos.eapi.insecure_http": (("eos", "2.9"),),
    "arista.eos.logging.remote_destination": (("eos", "1.1.7"),),
    "arista.eos.ntp.authentication": (("eos", "1.1.5"),),
    "arista.eos.ntp.servers": (("eos", "1.1.4"),),
    "arista.eos.routing.bgp.authentication": (("eos", "3.2.1"),),
    "arista.eos.routing.bgp.inbound_policy": (("eos", "3.2.1"),),
    "arista.eos.routing.bgp.missing_route_map": (("eos", "3.2.1"),),
    "arista.eos.routing.bgp.outbound_policy": (("eos", "3.2.1"),),
    "arista.eos.routing.bgp.permit_all_route_map": (("eos", "3.2.1"),),
    "arista.eos.routing.bgp.prefix_limit_disabled": (("eos", "3.2.1"),),
    "arista.eos.routing.ospf.authentication": (("eos", "3.1.1"),),
    "arista.eos.snmp.default_community": (("eos", "2.7.2"),),
    "arista.eos.snmp.secure_user_missing": (("eos", "2.7.3"),),
    "arista.eos.ssh.source_restriction": (("eos", "2.6.1"),),
    "arista.eos.ssh.weak_algorithms": (("eos", "2.6.3"),),
    "checkpoint.fw1.layer.explicit_cleanup_missing": (("checkpoint", "3.2"),),
    "checkpoint.fw1.layer.stealth_rule_missing": (("checkpoint", "3.1"),),
    "checkpoint.gaia.banner.login_disabled": (("checkpoint", "2.1.1"),),
    "checkpoint.gaia.cli.idle_timeout_excessive": (("checkpoint", "2.5.1"),),
    "checkpoint.gaia.management.telnet": (("checkpoint", "2.1.9"),),
    "checkpoint.gaia.management.unrestricted_allowed_client": (("checkpoint", "2.5.5"),),
    "checkpoint.gaia.password_policy.lockout_disabled": (("checkpoint", "1.11"),),
    "checkpoint.gaia.password_policy.lockout_threshold": (("checkpoint", "1.12"), ("checkpoint", "1.13")),
    "checkpoint.gaia.snmp.legacy_version": (("checkpoint", "2.2.2"),),
    "checkpoint.gaia.web.session_timeout_excessive": (("checkpoint", "2.5.2"),),
    "cisco.asa.aaa.management_accounting": (("asa", "1.4.5.1"), ("asa", "1.4.5.2"), ("asa", "1.4.5.3")),
    "cisco.asa.aaa.management_authentication": (("asa", "1.4.3.1"), ("asa", "1.4.3.2"), ("asa", "1.4.3.4")),
    "cisco.asa.admin.local_lockout_disabled": (("asa", "1.4.1.1"),),
    "cisco.asa.admin.local_password_minimum": (("asa", "1.1.5"),),
    "cisco.asa.asdm.idle_timeout_excessive": (("asa", "1.8.3"),),
    "cisco.asa.console.session_timeout": (("asa", "1.8.1"),),
    "cisco.asa.credentials.aaa_server_key_storage": (("asa", "1.1.3"),),
    "cisco.asa.credentials.known_default_value": (("asa", "1.1.1"), ("asa", "1.4.1.3")),
    "cisco.asa.credentials.local_user_storage": (("asa", "1.1.3"),),
    "cisco.asa.credentials.tunnel_group_pre_shared_key_storage": (("asa", "1.1.3"),),
    "cisco.asa.credentials.url_storage": (("asa", "1.1.3"),),
    "cisco.asa.credentials.weak_enable_password": (("asa", "1.1.2"),),
    "cisco.asa.interface.icmp_unrestricted": (("asa", "2.5"),),
    "cisco.asa.interface.reverse_path": (("asa", "3.7"),),
    "cisco.asa.logging.missing": (("asa", "1.10.1"),),
    "cisco.asa.logging.severity": (("asa", "1.10.9"),),
    "cisco.asa.management.http_sources": (("asa", "1.7.1"),),
    "cisco.asa.management.telnet": (("asa", "1.6.5"),),
    "cisco.asa.management.unrestricted_http": (("asa", "1.7.1"),),
    "cisco.asa.management.unrestricted_ssh": (("asa", "1.6.1"),),
    "cisco.asa.ntp.authentication": (("asa", "1.9.1.1"), ("asa", "1.9.1.2")),
    "cisco.asa.ntp.servers": (("asa", "1.9.1.3"),),
    "cisco.asa.snmp.default_community": (("asa", "1.11.5"),),
    "cisco.asa.snmp.legacy_version": (("asa", "1.11.3"),),
    "cisco.asa.snmp.v3_protection": (("asa", "1.11.1"),),
    "cisco.asa.snmp.v3_weak_algorithm": (("asa", "1.11.2"),),
    "cisco.asa.ssh.idle_timeout_excessive": (("asa", "1.8.2"),),
    "cisco.asa.ssh.protocol_version": (("asa", "1.6.2"),),
    "cisco.asa.threat_detection.basic": (("asa", "3.6"),),
    "cisco.asa.tls.minimum_version": (("asa", "1.7.2"),),
    "cisco.ios.aaa.accounting": (("iosxe17", "1.1.6"), ("iosxe17", "1.1.8")),
    "cisco.ios.aaa.login_authentication": (("iosxe17", "1.1.2"),),
    "cisco.ios.aaa.new_model": (("iosxe17", "1.1.1"),),
    "cisco.ios.auxiliary.enabled": (("iosxe17", "1.2.3"),),
    "cisco.ios.banner.login": (("iosxe17", "1.3.2"), ("iosxe17", "1.3.3")),
    "cisco.ios.credentials.enable_missing": (("iosxe17", "1.4.1"),),
    "cisco.ios.credentials.enable_storage": (("iosxe17", "1.4.1"), ("iosxe17", "1.4.3")),
    "cisco.ios.credentials.ftp_client_storage": (("iosxe17", "1.4.3"),),
    "cisco.ios.credentials.http_client_storage": (("iosxe17", "1.4.3"),),
    "cisco.ios.credentials.isakmp_pre_shared_key_storage": (("iosxe17", "1.4.3"),),
    "cisco.ios.credentials.keyring_pre_shared_key_storage": (("iosxe17", "1.4.3"),),
    "cisco.ios.credentials.local_storage": (("iosxe17", "1.4.3"),),
    "cisco.ios.credentials.local_user_storage": (("iosxe17", "1.4.3"),),
    "cisco.ios.credentials.tacacs_key_storage": (("iosxe17", "1.4.3"),),
    "cisco.ios.credentials.url_storage": (("iosxe17", "1.4.3"),),
    "cisco.ios.http.authentication": (("iosxe17", "1.1.5"),),
    "cisco.ios.interface.ip_hardening": (("iosxe17", "3.1.2"),),
    "cisco.ios.ip.source_route": (("iosxe17", "3.1.1"),),
    "cisco.ios.line.session_timeout_excessive": (("iosxe17", "1.2.6"), ("iosxe17", "1.2.7"), ("iosxe17", "1.2.8")),
    "cisco.ios.logging.remote_cleartext": (("iosxe17", "2.2.1"),),
    "cisco.ios.logging.remote_destination": (("iosxe17", "2.2.1"), ("iosxe17", "2.2.4")),
    "cisco.ios.logging.remote_weak_tls": (("iosxe17", "2.2.1"),),
    "cisco.ios.logging.severity": (("iosxe17", "2.2.1"), ("iosxe17", "2.2.5")),
    "cisco.ios.management.insecure_protocol": (("iosxe17", "1.2.2"),),
    "cisco.ios.ntp.authentication": (("iosxe17", "2.3.1.1"), ("iosxe17", "2.3.1.2"), ("iosxe17", "2.3.1.3"), ("iosxe17", "2.3.1.4")),
    "cisco.ios.ntp.servers": (("iosxe17", "2.3.2"),),
    "cisco.ios.routing.bgp.authentication": (("iosxe17", "3.3.3.1"),),
    "cisco.ios.routing.eigrp.authentication": (("iosxe17", "3.3.1.1"), ("iosxe17", "3.3.1.2"), ("iosxe17", "3.3.1.3"), ("iosxe17", "3.3.1.4"), ("iosxe17", "3.3.1.5"), ("iosxe17", "3.3.1.6"), ("iosxe17", "3.3.1.7"), ("iosxe17", "3.3.1.8"), ("iosxe17", "3.3.1.9")),
    "cisco.ios.routing.eigrp.key_resolution": (("iosxe17", "3.3.1.1"), ("iosxe17", "3.3.1.2"), ("iosxe17", "3.3.1.3"), ("iosxe17", "3.3.1.4"), ("iosxe17", "3.3.1.5"), ("iosxe17", "3.3.1.6"), ("iosxe17", "3.3.1.7"), ("iosxe17", "3.3.1.8"), ("iosxe17", "3.3.1.9")),
    "cisco.ios.routing.ospf.authentication": (("iosxe17", "3.3.2.1"), ("iosxe17", "3.3.2.2")),
    "cisco.ios.routing.rip.authentication": (("ios17", "3.3.3.4"), ("ios17", "3.3.3.5")),
    "cisco.ios.routing.rip.cleartext_authentication": (("ios17", "3.3.3.4"), ("ios17", "3.3.3.5")),
    "cisco.ios.routing.rip.key_resolution": (("ios17", "3.3.3.4"), ("ios17", "3.3.3.5")),
    "cisco.ios.routing.rip.version1_receive": (("ios17", "3.3.3.4"), ("ios17", "3.3.3.5")),
    "cisco.ios.routing.rip.version1_send": (("ios17", "3.3.3.4"), ("ios17", "3.3.3.5")),
    "cisco.ios.services.cns_config_cleartext": (("iosxe17", "2.1.3"),),
    "cisco.ios.services.default_enabled": (("iosxe17", "2.1.3"),),
    "cisco.ios.services.dns_lookup": (("iosxe17", "2.1.3"),),
    "cisco.ios.services.legacy_default": (("iosxe17", "2.1.3"),),
    "cisco.ios.services.remote_shell": (("iosxe17", "2.1.3"),),
    "cisco.ios.services.smart_install": (("iosxe17", "2.1.3"),),
    "cisco.ios.services.tcp_keepalives": (("iosxe17", "2.1.3"), ("iosxe17", "2.1.5"), ("iosxe17", "2.1.6")),
    "cisco.ios.services.tftp_boot_config": (("iosxe17", "2.1.3"),),
    "cisco.ios.services.tftp_server": (("iosxe17", "2.1.3"),),
    "cisco.ios.services.unnecessary": (("ios17", "2.1.5"), ("iosxe17", "2.1.3"), ("iosxe17", "2.1.7")),
    "cisco.ios.snmp.default_community": (("iosxe17", "1.5.2"), ("iosxe17", "1.5.3")),
    "cisco.ios.snmp.v3_access_scope": (("iosxe17", "1.5.9"),),
    "cisco.ios.snmp.v3_protection": (("iosxe17", "1.5.9"),),
    "cisco.ios.snmp.v3_reference": (("iosxe17", "1.5.9"),),
    "cisco.ios.snmp.v3_weak_algorithm": (("iosxe17", "1.5.9"), ("iosxe17", "1.5.10")),
    "cisco.ios.ssh.authentication_retries": (("iosxe17", "2.1.1.1.5"),),
    "cisco.ios.ssh.negotiation_timeout": (("iosxe17", "2.1.1.1.4"),),
    "cisco.ios.ssh.protocol_version": (("iosxe17", "2.1.1.2"),),
    "cisco.ios.ssh.vty_access_restriction": (("iosxe17", "1.2.5"),),
    "cisco.ios.ssh.weak_host_key": (("iosxe17", "2.1.1.1.3"),),
    "cisco.ios.vty.authentication": (("iosxe17", "1.1.4"),),
    "f5.bigip.auth.remote_default_admin": (("f5", "2.4"),),
    "f5.bigip.cli.audit_disabled": (("f5", "6.4"),),
    "f5.bigip.cli.idle_timeout_disabled": (("f5", "4.3"),),
    "f5.bigip.console.idle_timeout_disabled": (("f5", "4.4"),),
    "f5.bigip.credentials.known_default_value": (("f5", "1.1.1"), ("f5", "1.1.2")),
    "f5.bigip.http.legacy_tls_protocol": (("f5", "3.2"),),
    "f5.bigip.http.unrestricted_sources": (("f5", "3.3"),),
    "f5.bigip.logging.syslog_remote_none": (("f5", "6.5"),),
    "f5.bigip.management.self_ip_port_lockdown": (("f5", "5.3"),),
    "f5.bigip.password_policy.enforcement_disabled": (("f5", "1.1.3"),),
    "f5.bigip.password_policy.minimum_length_disabled": (("f5", "1.1.3"),),
    "f5.bigip.snmp.community_access": (("f5", "6.1"),),
    "f5.bigip.snmp.legacy_version": (("f5", "6.2"),),
    "f5.bigip.ssh.idle_timeout_disabled": (("f5", "4.2"),),
    "f5.bigip.ssh.unrestricted_sources": (("f5", "4.8"),),
    "fortinet.fortios.admin.lockout": (("fortigate74", "2.2.2"),),
    "fortinet.fortios.admin.session_timeout": (("fortigate74", "2.4.4"),),
    "fortinet.fortios.admin.trusted_hosts": (("fortigate74", "2.4.2"),),
    "fortinet.fortios.banner.login_disabled": (("fortigate74", "2.1.1"),),
    "fortinet.fortios.crypto.ssl_static_key_ciphers": (("fortigate74", "2.1.8"),),
    "fortinet.fortios.crypto.strong_crypto": (("fortigate74", "2.1.9"),),
    "fortinet.fortios.dnsfilter.botnet_blocking_disabled": (("fortigate74", "4.3.1"),),
    "fortinet.fortios.hardening.cis_hygiene": (("fortigate74", "3.3"), ("fortigate74", "4.3.2")),
    "fortinet.fortios.logging.events_filtered": (("fortigate74", "7.1.1"),),
    "fortinet.fortios.logging.missing": (("fortigate74", "7.2.1"),),
    "fortinet.fortios.logging.remote_cleartext": (("fortigate74", "7.3.2"), ("fortigate74", "7.3.3")),
    "fortinet.fortios.logging.remote_identity_unverified": (("fortigate74", "7.3.1"),),
    "fortinet.fortios.logging.remote_weak_tls": (("fortigate74", "7.3.1"),),
    "fortinet.fortios.management.insecure_protocol": (("fortigate74", "2.4.5"),),
    "fortinet.fortios.ntp.synchronization": (("fortigate74", "2.1.4"),),
    "fortinet.fortios.password_policy.disabled": (("fortigate74", "2.2.1"),),
    "fortinet.fortios.password_policy.weak": (("fortigate74", "2.2.1"),),
    "fortinet.fortios.policy.logging": (("fortigate74", "3.4"),),
    "fortinet.fortios.policy.security_profiles": (("fortigate74", "4.1.2"), ("fortigate74", "4.2.2")),
    "fortinet.fortios.snmp.legacy_community": (("fortigate74", "2.3.1"),),
    "fortinet.fortios.snmp.legacy_version": (("fortigate74", "2.3.1"),),
    "fortinet.fortios.sslvpn.factory_certificate": (("fortigate74", "6.1.1"),),
    "fortinet.fortios.sslvpn.legacy_tls": (("fortigate74", "6.1.2"),),
    "fortinet.fortios.system.usb_auto_install": (("fortigate74", "2.1.7"),),
    "fortinet.fortios.tls.minimum_version": (("fortigate74", "2.1.10"),),
    "juniper.junos.administration.web_session_limit": (("junos", "6.10.2.5"),),
    "juniper.junos.administration.web_session_timeout": (("junos", "6.10.2.4"),),
    "juniper.junos.authentication.accounting_destination": (("junos", "6.1.1"),),
    "juniper.junos.authentication.accounting_events": (("junos", "6.1.2"), ("junos", "6.1.3"), ("junos", "6.1.4")),
    "juniper.junos.authentication.centralized": (("junos", "6.3.1"), ("junos", "6.8.1")),
    "juniper.junos.authentication.idle_timeout": (("junos", "6.6.3"),),
    "juniper.junos.authentication.lockout": (("junos", "6.6.1.1"), ("junos", "6.6.1.2"), ("junos", "6.6.1.3"), ("junos", "6.6.1.4"), ("junos", "6.6.1.5")),
    "juniper.junos.authentication.login_banner": (("junos", "6.6.8"),),
    "juniper.junos.authentication.login_class_binding": (("junos", "6.6.2"),),
    "juniper.junos.authentication.weak_storage": (("junos", "6.6.12"),),
    "juniper.junos.configuration.archive_incomplete": (("junos", "6.2.2"),),
    "juniper.junos.configuration.archive_required": (("junos", "6.2.1"),),
    "juniper.junos.configuration.archive_transport": (("junos", "6.2.3"),),
    "juniper.junos.control_plane.lo0_filter": (("junos", "2.1"), ("junos", "3.10")),
    "juniper.junos.fhrp.authentication": (("junos", "3.2.1"), ("junos", "3.2.2")),
    "juniper.junos.hardening.cis_hygiene": (("junos", "3.7"), ("junos", "5.3"), ("junos", "5.8"), ("junos", "6.6.9"), ("junos", "6.6.10"), ("junos", "6.6.11"), ("junos", "6.22")),
    "juniper.junos.interfaces.redirects": (("junos", "3.6"), ("junos", "6.21")),
    "juniper.junos.logging.remote_destination": (("junos", "6.12.1"), ("junos", "6.12.2")),
    "juniper.junos.management.insecure_protocol": (("junos", "6.10.2.1"), ("junos", "6.10.6")),
    "juniper.junos.management.rest_http": (("junos", "6.10.5.1"),),
    "juniper.junos.ntp.associations": (("junos", "6.7.1"), ("junos", "6.7.2")),
    "juniper.junos.ntp.authentication": (("junos", "6.7.5"), ("junos", "6.7.6"), ("junos", "6.7.7")),
    "juniper.junos.routing.bgp.authentication": (("junos", "4.1.1"),),
    "juniper.junos.routing.isis.authentication": (("junos", "4.2.1"), ("junos", "4.2.2")),
    "juniper.junos.routing.isis.send_only": (("junos", "4.2.3"),),
    "juniper.junos.routing.ospf.authentication": (("junos", "4.3.1"), ("junos", "4.3.2")),
    "juniper.junos.services.legacy": (("junos", "6.10.3.1"), ("junos", "6.10.8"), ("junos", "6.10.9")),
    "juniper.junos.snmp.legacy_community": (("junos", "5.1"), ("junos", "5.2"), ("junos", "5.5")),
    "juniper.junos.snmp.v3_security": (("junos", "5.6"), ("junos", "5.7")),
    "juniper.junos.ssh.root_login": (("junos", "6.10.1.5"),),
    "paloalto.panos.admin.idle_timeout": (("panos11", "1.4.1"),),
    "paloalto.panos.admin.login_attempts": (("panos11", "1.4.2"),),
    "paloalto.panos.admin.login_banner": (("panos11", "1.1.2"),),
    "paloalto.panos.credentials.password_complexity": (("panos11", "1.3.1"), ("panos11", "1.3.2"), ("panos11", "1.3.3"), ("panos11", "1.3.4"), ("panos11", "1.3.5"), ("panos11", "1.3.6")),
    "paloalto.panos.credentials.password_history_disabled": (("panos11", "1.3.9"),),
    "paloalto.panos.logging.system_forwarding": (("panos11", "1.1.1.1"),),
    "paloalto.panos.management.certificate_algorithm": (("panos11", "1.2.5"),),
    "paloalto.panos.management.certificate_identity": (("panos11", "1.2.5"),),
    "paloalto.panos.management.certificate_material_malformed": (("panos11", "1.2.5"),),
    "paloalto.panos.management.certificate_missing": (("panos11", "1.2.5"),),
    "paloalto.panos.management.certificate_trust": (("panos11", "1.2.5"),),
    "paloalto.panos.management.certificate_unresolved": (("panos11", "1.2.5"),),
    "paloalto.panos.management.certificate_validity": (("panos11", "1.2.5"),),
    "paloalto.panos.management.http": (("panos11", "1.2.3"), ("panos11", "1.2.4")),
    "paloalto.panos.management.unrestricted_secure_service": (("panos11", "1.2.1"), ("panos11", "1.2.2")),
    "paloalto.panos.ntp.servers": (("panos11", "1.6.2"),),
    "paloalto.panos.policy.broad_service": (("panos11", "7.2"),),
    "paloalto.panos.policy.security_profiles": (("panos11", "6.1"), ("panos11", "6.2")),
    "paloalto.panos.policy.threat_selector_nonblocking": (("panos11", "6.3"), ("panos11", "6.6")),
    "paloalto.panos.profile.dns_sinkhole": (("panos11", "6.4"),),
    "paloalto.panos.zone.scan_allow": (("panos11", "6.17"),),
    "paloalto.panos.zone.syn_flood_disabled": (("panos11", "6.15"), ("panos11", "6.16")),
}


def cis_references(rule_id: str) -> tuple[str, ...]:
    """Display strings such as "CIS Juniper OS Benchmark v2.1.0 5.6" for one rule."""
    return tuple(f"{CIS_BENCHMARKS[key]} {number}" for key, number in CIS_RULE_REFERENCES.get(rule_id, ()))


def cis_references_for_rules(rule_ids) -> list[str]:
    seen: list[str] = []
    for rule_id in rule_ids:
        for item in cis_references(rule_id):
            if item not in seen:
                seen.append(item)
    return seen
